
SHELL := cmd.exe
.SHELLFLAGS := /C

CC := C:/raylib/w64devkit/bin/gcc.exe

SRC_DIR := src
SQLITE_DIR := third_party/sqlite
RAYLIB_DIR := C:/raylib/raylib/src

MODE ?= debug

ifeq ($(MODE),release)
BUILD_DIR := build/release
APP_FLAGS := -O2 -DNDEBUG
else
BUILD_DIR := build/debug
APP_FLAGS := -O0 -g3
endif

TARGET := $(BUILD_DIR)/mapboard.exe


# ------------------------------------------------------------
# Source files
# ------------------------------------------------------------

# Automatically find every .c file inside src/
SOURCES := $(wildcard $(SRC_DIR)/*.c)

# Convert:
# src/main.c   -> build/debug/main.o
# src/geo.c    -> build/debug/geo.o
# src/tile_db.c -> build/debug/tile_db.o
OBJECTS := \
	$(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SOURCES)) \
	$(BUILD_DIR)/sqlite3.o

DEPENDENCIES := $(OBJECTS:.o=.d)


# ------------------------------------------------------------
# Compiler flags
# ------------------------------------------------------------

CPPFLAGS := \
	-I$(SRC_DIR) \
	-I$(SQLITE_DIR) \
	-I$(RAYLIB_DIR) \
	-DSQLITE_THREADSAFE=1

COMMON_FLAGS := \
	-std=c11 \
	-MMD \
	-MP

APP_WARNINGS := \
	-Wall \
	-Wextra \
	-Wpedantic

SQLITE_FLAGS := \
	-O2 \
	-DNDEBUG


# ------------------------------------------------------------
# Linker flags
# ------------------------------------------------------------

LDFLAGS := -L$(RAYLIB_DIR)

LDLIBS := \
	-lraylib \
	-lopengl32 \
	-lgdi32 \
	-lwinmm


# ------------------------------------------------------------
# Targets
# ------------------------------------------------------------

.PHONY: all app debug release run clean rebuild

all: app

app: $(TARGET)

debug:
	$(MAKE) MODE=debug app

release:
	$(MAKE) MODE=release app

run:
	$(MAKE) MODE=debug app
	$(TARGET)

rebuild:
	$(MAKE) clean
	$(MAKE) MODE=$(MODE) app


# ------------------------------------------------------------
# Link application
# ------------------------------------------------------------

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS) $(LDLIBS)


# ------------------------------------------------------------
# Compile project source files
# ------------------------------------------------------------

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CPPFLAGS) $(COMMON_FLAGS) $(APP_WARNINGS) $(APP_FLAGS) -c $< -o $@


# ------------------------------------------------------------
# Compile SQLite separately
# ------------------------------------------------------------

$(BUILD_DIR)/sqlite3.o: $(SQLITE_DIR)/sqlite3.c $(SQLITE_DIR)/sqlite3.h | $(BUILD_DIR)
	$(CC) $(CPPFLAGS) $(COMMON_FLAGS) $(SQLITE_FLAGS) -c $< -o $@


# ------------------------------------------------------------
# Create build directory
# ------------------------------------------------------------

$(BUILD_DIR):
	if not exist "$@" mkdir "$@"


# ------------------------------------------------------------
# Clean
# ------------------------------------------------------------

clean:
	if exist build rmdir /S /Q build


# ------------------------------------------------------------
# Dependency files generated by -MMD
# ------------------------------------------------------------

-include $(DEPENDENCIES)